# Generated by Django 5.1 on 2024-08-23 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('depth', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_hierarchy.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'depth'], name='menu_hierar_name_322fc8_idx'), models.Index(fields=['parent', 'depth'], name='menu_hierar_parent__e8316d_idx'), models.Index(fields=['created_at', 'updated_at'], name='menu_hierar_created_c560e5_idx')],
            },
        ),
    ]
