# Generated by Django 5.1 on 2024-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
