# Generated by Django 5.1 on 2024-08-22 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_hierarchy', '0002_remove_menuitem_title_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='depth',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name', 'depth'], name='menu_hierar_name_322fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent', 'depth'], name='menu_hierar_parent__e8316d_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['created_at', 'updated_at'], name='menu_hierar_created_c560e5_idx'),
        ),
    ]
